<div style="background-color:#e6f2ff; padding:20px; border-radius:10px;">
<img style="float:left; margin-right:20px;" src='Figures/alinco.png' width="120"/>
<h1 style="color:#000047;">Actividad 1: Implementación de un modelo por Random Forest</h1>
<br style="clear:both"/>
</div>

<div style="border-left:4px solid #000047; padding:10px; margin-top:10px; background:#f5f5f5;">
<b>Objetivo:</b> En esta actividad construiras un clasificadore basados en **Random Forest** para predecir la **aceptabilidad/seguridad de un automóvil**. 
</div>

<div style="margin-top:10px;">
<b>Instrucciones generales:</b>
<ul>
<li>Entrenar dos modelos (con pocos y con muchos árboles) para observar cómo mejora la exactitud, demostrar el proceso de **selección de características** basado en la importancia de variables, y reconstruir el modelo con las variables más relevantes. </li>

</ul>
</div>

**Random Forest** (bosque aleatorio) es un algoritmo de **aprendizaje supervisado** basado en **ensamble** (*ensemble learning*). Tiene dos variantes: una para **clasificación** y otra para **regresión**. Es uno de los algoritmos más flexibles y fáciles de usar.

Construye **múltiples árboles de decisión** sobre distintas muestras de los datos, obtiene la predicción de cada árbol y selecciona la mejor solución mediante **votación**. Además, es un excelente indicador de la **importancia de las variables**.

> Al combinar muchos árboles se forma un "bosque"; de ahí el nombre **Random Forest**. Cuantos **más árboles**, mayor suele ser la exactitud (hasta estabilizarse).

#### Selección de características con Random Forest

El Random Forest permite **ordenar la importancia** de las variables. Durante el entrenamiento, se registra el **error out-of-bag (OOB)** y se promedia sobre el bosque.

Para medir la importancia de la característica *j*, se **permutan** sus valores en los datos y se recalcula el error OOB sobre ese conjunto perturbado. La **importancia** es la diferencia promedio de error OOB antes y después de la permutación, normalizada por su desviación estándar.

Las características que producen valores **grandes** de esta puntuación son más importantes. Con base en ella, conservaremos las más relevantes y descartaremos las menos útiles.

**Planteamiento del problema**

El objetivo es **predecir la aceptabilidad/seguridad de un automóvil** con un clasificador Random Forest en Python y scikit-learn, usando el [**Car Evaluation Data Set**](http://archive.ics.uci.edu/ml/datasets/Car+Evaluation) de la UCI.

El **Car Evaluation Data Set** relaciona la evaluación del automóvil (`class`) con **seis atributos de entrada**:

| Variable | Descripción | Valores |
|---|---|---|
| `buying` | Precio de compra | vhigh, high, med, low |
| `maint` | Costo de mantenimiento | vhigh, high, med, low |
| `doors` | Número de puertas | 2, 3, 4, 5more |
| `persons` | Capacidad de personas | 2, 4, more |
| `lug_boot` | Tamaño de la cajuela | small, med, big |
| `safety` | Seguridad estimada | low, med, high |
| `class` | **Objetivo:** evaluación | unacc, acc, good, vgood |

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

import warnings
warnings.filterwarnings('ignore')

In [2]:
# Dataset real de la UCI (se descarga al vuelo)
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/car/car.data'
df = pd.read_csv(url, header=None)

# Alternativa local: df = pd.read_csv('C:/datasets/car.data', header=None)
df.shape

(1728, 7)

## 1.- Análisis exploratorio de datos

In [3]:
# Primeras filas (columnas aún sin nombre)
df.head()

       0      1  2  3      4     5      6
0  vhigh  vhigh  2  2  small   low  unacc
1  vhigh  vhigh  2  2  small   med  unacc
2  vhigh  vhigh  2  2  small  high  unacc
3  vhigh  vhigh  2  2    med   low  unacc
4  vhigh  vhigh  2  2    med   med  unacc

In [4]:
col_names = ['buying', 'maint', 'doors', 'persons', 'lug_boot', 'safety', 'class']
df.columns = col_names
df.head()

  buying  maint doors persons lug_boot safety  class
0  vhigh  vhigh     2       2    small    low  unacc
1  vhigh  vhigh     2       2    small    med  unacc
2  vhigh  vhigh     2       2    small   high  unacc
3  vhigh  vhigh     2       2      med    low  unacc
4  vhigh  vhigh     2       2      med    med  unacc

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1728 entries, 0 to 1727
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   buying    1728 non-null   object
 1   maint     1728 non-null   object
 2   doors     1728 non-null   object
 3   persons   1728 non-null   object
 4   lug_boot  1728 non-null   object
 5   safety    1728 non-null   object
 6   class     1728 non-null   object
dtypes: object(7)
memory usage: 94.6+ KB

In [6]:
# Distribución de frecuencias
df['persons'].value_counts()

persons
2       576
4       576
more    576
Name: count, dtype: int64

In [7]:
for col in df.columns:
    print(df[col].value_counts())

buying
vhigh    432
high     432
med      432
low      432
Name: count, dtype: int64
maint
vhigh    432
high     432
med      432
low      432
Name: count, dtype: int64
doors
2        432
3        432
4        432
5more    432
Name: count, dtype: int64
persons
2       576
4       576
more    576
Name: count, dtype: int64
lug_boot
small    576
med      576
big      576
Name: count, dtype: int64
safety
low     576
med     576
high    576
Name: count, dtype: int64
class
unacc    1210
acc       384
good       69
vgood      65
Name: count, dtype: int64

### Variable objetivo `class` y valores faltantes
La variable objetivo es **ordinal** (unacc < acc < good < vgood).

In [9]:
df.isnull().sum()

buying      0
maint       0
doors       0
persons     0
lug_boot    0
safety      0
class       0
dtype: int64

## 2. Definir variables predictoras y objetivo

In [10]:
X = df.drop(['class'], axis=1)
y = df['class']

In [11]:
X

     buying  maint  doors persons lug_boot safety
0     vhigh  vhigh      2       2    small    low
1     vhigh  vhigh      2       2    small    med
2     vhigh  vhigh      2       2    small   high
3     vhigh  vhigh      2       2      med    low
4     vhigh  vhigh      2       2      med    med
...     ...    ...    ...     ...      ...    ...
1723    low    low  5more    more      med    med
1724    low    low  5more    more      med   high
1725    low    low  5more    more      big    low
1726    low    low  5more    more      big    med
1727    low    low  5more    more      big   high

[1728 rows x 6 columns]

In [12]:
y

0       unacc
1       unacc
2       unacc
3       unacc
4       unacc
        ...
1723     good
1724    vgood
1725    unacc
1726     good
1727    vgood
Name: class, Length: 1728, dtype: object

## 3. Dividir en entrenamiento y prueba

In [16]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 42)

In [17]:
X_train.shape, y_train.shape

((1382, 6), (1382,))

In [18]:
X_test.shape, y_test.shape

((346, 6), (346,))

## 4. Ingeniería de características (codificación)

Todas las variables son **categóricas ordinales**; las convertimos a números con `OrdinalEncoder` de scikit-learn (sin dependencias externas).

In [19]:
from sklearn.preprocessing import OrdinalEncoder

In [20]:
encoder = OrdinalEncoder()

In [24]:
X_train_num = pd.DataFrame(encoder.fit_transform(X_train), columns = X.columns, index = X_train.index)
X_train_num

      buying  maint  doors  persons  lug_boot  safety
107      3.0    3.0    3.0      2.0       0.0     0.0
901      2.0    3.0    1.0      1.0       2.0     2.0
1709     1.0    1.0    3.0      0.0       0.0     0.0
706      0.0    2.0    2.0      0.0       1.0     2.0
678      0.0    2.0    1.0      0.0       1.0     1.0
...      ...    ...    ...      ...       ...     ...
1130     2.0    2.0    1.0      2.0       1.0     0.0
1294     2.0    1.0    3.0      2.0       0.0     2.0
860      0.0    1.0    3.0      2.0       1.0     0.0
1459     1.0    0.0    2.0      0.0       2.0     2.0
1126     2.0    2.0    1.0      2.0       2.0     2.0

[1382 rows x 6 columns]

In [25]:
X_test_num = pd.DataFrame(encoder.fit_transform(X_test), columns = X.columns, index = X_test.index)
X_test_num

      buying  maint  doors  persons  lug_boot  safety
599      0.0    0.0    2.0      0.0       1.0     0.0
1201     2.0    1.0    0.0      1.0       1.0     2.0
628      0.0    0.0    3.0      0.0       0.0     2.0
1498     1.0    0.0    3.0      1.0       1.0     2.0
1263     2.0    1.0    2.0      2.0       1.0     1.0
...      ...    ...    ...      ...       ...     ...
100      3.0    3.0    3.0      2.0       2.0     2.0
274      3.0    2.0    2.0      0.0       1.0     2.0
1206     2.0    1.0    0.0      2.0       2.0     1.0
101      3.0    3.0    3.0      2.0       2.0     0.0
1084     2.0    2.0    0.0      0.0       1.0     2.0

[346 rows x 6 columns]

In [29]:
y_train

107     unacc
901     unacc
1709    unacc
706     unacc
678     unacc
        ...
1130    vgood
1294     good
860       acc
1459    unacc
1126      acc
Name: class, Length: 1382, dtype: object

## 5. Random Forest con pocos árboles (modelo 1)

Entrena un bosque con **10 árboles** para tener una referencia.

In [32]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score

In [33]:
#Arbol de referencia
tree = DecisionTreeClassifier(random_state=0).fit(X_train_num, y_train)

rfc = RandomForestClassifier(n_estimators = 10, random_state = 42) # Agregar parametros como max_features, oob_score, n_jobs
rfc.fit(X_train_num, y_train)

RandomForestClassifier(n_estimators=10, random_state=42)

In [34]:
y_pred = rfc.predict(X_train_num)

In [35]:
y_pred

array(['unacc', 'unacc', 'unacc', ..., 'acc', 'unacc', 'acc'],
      shape=(1382,), dtype=object)

In [ ]:
# Accuracy del arbol de referencia tree.predict(X_test) con y_test
#Accuracy y_train, y_pred
#Accuracy y_test, y_pred_test = rfc.predict(X_test_num)

## 6. Random Forest con muchos arboles `n_estimators=100`

Entrena un modelo con **100 árboles** y comenta lo que puedas observar.

## 7. Importancia de las características

Usa el atributo `feature_importances_` del bosque para ordenar las variables por relevancia.

## 8. Visualizar la importancia de las características

## 9. Reconstruir el modelo con las características seleccionadas

Elimina la variable **menos importante**, reconstruye el modelo y compara la exactitud.

In [ ]:
# Nuevo conjunto de variables sin 'doors'

## 10. Crea un Reporte de clasificación

Muestra **precision**, **recall**, **f1-score** y **support** por clase.